services:
  servers:
    build: .
    command: "node dist/index.js"
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - "./package.json:/code/package.json"
      - "./package-lock.json:/code/package-lock.json"
      - "./tsconfig.json:/code/tsconfig.json"
      - "./src:/code/src:ro"
      - "./servers:/code/servers"
      - "./dist:/code/dist"
    init: true